spring:
  datasource:
    url: jdbc:mysql://umc-6th-db2.cl82ocsm6x6u.ap-northeast-2.rds.amazonaws.com:3306/umc_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: umc6thpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000